version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build: .
    container_name: rq_worker
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis
